apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: black-sheep
  annotations:
    type: PWN
    name: Black Sheep
    description: "https://twitter.com/SuplabsYi/status/1717665382960595251"
    author: "Yi (@SuplabsYi) at Supremacy (@SupremacyHQ)"
    tags: "pwn,huff"
    flag: "PCTF{7rU57_8u7_vEr1fy}"
spec:
  deployed: true
  powDifficultySeconds: 0
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
    image: kind/healthcheck:938a93f31c9d0b6bc2ba5e23dd9a06aaaa372b6c7d06eedba66a3c920117b130
  image: gcr.io/paradigm-ctf/black-sheep-challenge:9d755b6276db9ea180dabf77299a42ba4ab9ca3f590a871ebc54548a2dfb0a3c
