name: paradigm-ctf-challenge
services:
  dummy-foundry:
    container_name: dummy-foundry
    image: gcr.io/paradigm-ctf/enterprise-blockchain-anvil:latest
    build: foundry
    entrypoint: "/bin/true"
  dummy-relayer:
    container_name: dummy-relayer
    image: gcr.io/paradigm-ctf/enterprise-blockchain-relayer:latest
    build: relayer
    entrypoint: "/bin/true"
  launcher:
    container_name: challenge
    image: challenge
    build:
      context: .
      target: chroot
    command: socat TCP-LISTEN:1337,reuseaddr,fork exec:"python3 -u challenge/challenge.py"
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network
    environment:
      - ETH_RPC_URL=https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
networks:
  ctf_network:
    name: paradigmctf
    external: true