[profile.default]
src = 'src'
libs = ['lib']
fs_permissions = [{ access = 'read-write', path = '/'}]

remappings = [
    "forge-std=lib/forge-std/src",
    "forge-ctf=lib/forge-ctf/src",
    "@openzeppelin=lib/openzeppelin-contracts",
    "@uniswap/merkle-distributor=lib/merkle-distributor",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config