apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: dodont
  annotations:
    type: PWN
    name: DODONT
    description: Sometimes all it takes is knowing where to look
    author: "samczsun"
    tags: "pwn"
    flag: "PCTF{UNpr0t3cT3D_INITI4Liz3Rs_4r3_s0_L4ST_Y34R}"
spec:
  deployed: true
  powDifficultySeconds: 0
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
    image: kind/healthcheck:938a93f31c9d0b6bc2ba5e23dd9a06aaaa372b6c7d06eedba66a3c920117b130
  image: gcr.io/paradigm-ctf/dodont-challenge:111bb6b2408c79f354d2c8cf7aeddc11c5d6cf7753b199c326ed9e3bbe12486f
